import type { Metadata } from "next";
import TanStackProvider from "../components/TanStackProvider/TanStackProvider";
import Header from "@/components/Header/Header";
import Footer from "@/components/Footer/Footer";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
  modal,
}: Readonly<{
  children: React.ReactNode;
  modal: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body>

        <TanStackProvider>

          <Header />

          <main>
            {children}
            {modal}
          </main>

          <Footer />

          <div id="modal-root"></div>
        </TanStackProvider>

      </body>
    </html>
  );
}
